version: '3.8'

services:
  db:
    image: velheor1/prologdb
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    container_name: prologdb